# Generated by Django 3.2.8 on 2021-10-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='name',
            new_name='cityName',
        ),
    ]
